sudo: required
language: cpp
dist: trusty

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6

before_script:
    - sudo apt-get install cmake -y

script:

    # binary build

    - mkdir build && cd build/
    # force the compiler version on Ubuntu Trusty,
    # Travis-CI newest OS is Trusty;
    # forcing the compiler binary might not
    # be required on other systems
    - cmake -D CMAKE_CXX_COMPILER=g++-6 ..
    - make

    # run unit tests

    - cd ../ && mkdir libs/
    - g++-6 -c -I includes src/playlist.cpp -o libs/playlist.o -lpthread
    - g++-6 -c -I includes src/track.cpp -o libs/track.o
    - g++-6 -I includes tests/unit_tests.cpp -o bin/unit_tests libs/* -lpthread
    - ./bin/unit_tests

    # run functionnal tests

    - ./tests/functionnal_tests.sh
