sudo: required
language: cpp
dist: trusty

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6

before_script:
    - sudo apt-get install cmake -y

script: 
    - mkdir build && cd build/
    # force the compiler version on Ubuntu Trusty,
    # Travis-CI newest OS is Trusty;
    # forcing the compiler binary might not
    # be required on other systems
    - cmake -D CMAKE_CXX_COMPILER=g++-6 ..
    - make
